### ISSUE TITLE
Gnome 3.26 on Arch Linux

### ISSUE THREAD

**Issue by tonylambiris** [martin31821/cpupower#49]
I am the maintainer of this extension for Arch Linux, been debugging why it doesn't work in 3.26 and hoping this issue can help track that:

```
Oct 14 06:15:23 holodeck.local gnome-shell[8065]: JS WARNING: [/usr/share/gnome-shell/extensions/cpupower@mko-sl.de/src/indicator.js 67]: reference to undefined property "out"
Oct 14 06:15:23 holodeck.local gnome-shell[8065]: JS WARNING: [/usr/share/gnome-shell/extensions/cpupower@mko-sl.de/src/indicator.js 67]: Too many arguments to function GLib.spawn_command_line_sync: expected 1, got 2
Oct 14 06:15:23 holodeck.local gnome-shell[8065]: JS WARNING: [/usr/share/gnome-shell/extensions/cpupower@mko-sl.de/src/indicator.js 71]: Too many arguments to function GLib.spawn_command_line_sync: expected 1, got 2
Oct 14 06:15:23 holodeck.local gnome-shell[8065]: JS WARNING: [/usr/share/gnome-shell/extensions/cpupower@mko-sl.de/src/indicator.js 75]: Too many arguments to function GLib.spawn_command_line_sync: expected 1, got 2
Oct 14 06:15:23 holodeck.local gnome-shell[8065]: JS WARNING: [/usr/share/gnome-shell/extensions/cpupower@mko-sl.de/src/indicator.js 153]: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
Oct 14 06:15:23 holodeck.local gnome-shell[8065]: JS WARNING: [/usr/share/gnome-shell/extensions/cpupower@mko-sl.de/src/indicator.js 157]: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
Oct 14 06:15:23 holodeck.local gnome-shell[8065]: JS WARNING: [/usr/share/gnome-shell/extensions/cpupower@mko-sl.de/src/indicator.js 189]: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
```

**Comment by tonylambiris** [comment]
https://github.com/martin31821/cpupower/pull/50
